name: Gerar APK Manual
on:
  workflow_dispatch: # Permite que você clique em um botão para gerar o APK

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalar Expo CLI e EAS
        run: npm install -g expo-cli eas-cli

      - name: Instalar dependências
        run: npm install

      - name: Fazer o Prebuild (Gera a pasta Android)
        run: npx expo prebuild --platform android

      - name: Gerar o APK via Gradle
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Salvar o APK gerado
        uses: actions/upload-artifact@v4
        with:
          name: meu-app-prime
          path: android/app/build/outputs/apk/release/app-release.apk
          
